# generated by datamodel-codegen:
#   filename:  xsg-pattern.schema.json
#   timestamp: 2025-11-11T05:22:08+00:00
#
# XSG Pattern Format - Pydantic Models
# Auto-generated from JSON Schema, with manual adjustments
#
# To regenerate:
#   cd backend
#   uv run datamodel-codegen \
#     --input ../xsg-pattern.schema.json \
#     --output app/models.py \
#     --input-file-type jsonschema \
#     --output-model-type pydantic_v2.BaseModel
#
# Manual adjustments after generation:
#   - Renamed Direction1 → AnimationDirection
#   - Renamed XsgPatternFormat → XSGPattern
#   - Added PatternNode type alias

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, RootModel, confloat, conint, constr


class Canvas(BaseModel):
    width: conint(ge=1) = Field(..., description='Canvas width in pixels')
    height: conint(ge=1) = Field(..., description='Canvas height in pixels')


class Coordinate(
    RootModel[Union[float, constr(pattern=r'^(\d+(\.\d+)?%|calc\(.+\))$')]]
):
    root: Union[float, constr(pattern=r'^(\d+(\.\d+)?%|calc\(.+\))$')] = Field(
        ..., description='Coordinate: number (pixels) or string (%, calc())'
    )


class Color(RootModel[constr(pattern=r'^#[0-9A-Fa-f]{6}$')]):
    root: constr(pattern=r'^#[0-9A-Fa-f]{6}$') = Field(
        ..., description='Color in hex format (#RRGGBB)'
    )


class Direction(Enum):
    horizontal = 'horizontal'
    vertical = 'vertical'


class Fit(Enum):
    contain = 'contain'
    cover = 'cover'
    fill = 'fill'


class Easing(Enum):
    linear = 'linear'
    ease = 'ease'
    ease_in = 'ease-in'
    ease_out = 'ease-out'
    ease_in_out = 'ease-in-out'


class AnimationDirection(Enum):
    normal = 'normal'
    reverse = 'reverse'
    alternate = 'alternate'
    alternate_reverse = 'alternate-reverse'


class Animation(BaseModel):
    keyframes: Optional[List[Dict[str, Any]]] = Field(
        None, description='Keyframes (WAAPI: Array of Objects format)'
    )
    props: Optional[Dict[str, List]] = Field(
        None, description='Props (WAAPI: Object with Arrays format, sugar syntax)'
    )
    duration: confloat(ge=0.0) = Field(
        ..., description='Animation duration in milliseconds'
    )
    iterations: Optional[Union[confloat(ge=1.0), str]] = Field(
        None, description="Number of iterations or 'Infinity'"
    )
    easing: Optional[Easing] = Field(None, description='Easing function (WAAPI)')
    delay: Optional[confloat(ge=0.0)] = Field(
        None, description='Delay before animation starts (ms)'
    )
    direction: Optional[AnimationDirection] = Field(
        None, description='Animation direction (WAAPI)'
    )


class BaseNode(BaseModel):
    id: str = Field(..., description='Unique identifier for this node')
    type: str = Field(..., description='Node type')
    fill: Optional[Color] = Field(None, description='Fill color (p5.js: fill())')
    stroke: Optional[Color] = Field(None, description='Stroke color (p5.js: stroke())')
    strokeWidth: Optional[confloat(ge=0.0)] = Field(
        None, description='Stroke width (p5.js: strokeWeight())'
    )
    opacity: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None, description='Opacity (CSS: opacity, 0-1)'
    )
    blur: Optional[confloat(ge=0.0)] = Field(
        None, description='Blur radius in pixels (CSS: filter: blur())'
    )
    rotate: Optional[confloat(ge=0.0, le=360.0)] = Field(
        None, description='Rotation angle in degrees'
    )
    blink: Optional[confloat(ge=0.0)] = Field(
        None, description='Blink interval in milliseconds'
    )
    animation: Optional[Animation] = None


class BackgroundNode(BaseNode):
    type: Literal['background'] = 'background'
    preset: Optional[str] = Field(None, description='Preset name (from presets/ directory)')
    params: Optional[Dict[str, Any]] = Field(
        None, description='Preset-specific parameters'
    )


class RectNode(BaseNode):
    type: Literal['rect'] = 'rect'
    x: Coordinate
    y: Coordinate
    width: Coordinate
    height: Coordinate


class CircleNode(BaseNode):
    type: Literal['circle'] = 'circle'
    x: Coordinate
    y: Coordinate
    diameter: confloat(ge=0.0) = Field(
        ..., description='Circle diameter (p5.js: circle(x,y,d))'
    )


class EllipseNode(BaseNode):
    type: Literal['ellipse'] = 'ellipse'
    x: Coordinate
    y: Coordinate
    width: confloat(ge=0.0)
    height: confloat(ge=0.0)


class LineNode(BaseNode):
    type: Literal['line'] = 'line'
    x1: Coordinate
    y1: Coordinate
    x2: Coordinate
    y2: Coordinate


class DirectedLineNode(BaseNode):
    type: Literal['directedLine'] = 'directedLine'
    x: Coordinate
    y: Coordinate
    direction: Direction = Field(..., description='Line direction')
    length: confloat(ge=0.0) = Field(..., description='Line length in pixels')


class ImageNode(BaseNode):
    type: Literal['image'] = 'image'
    src: str = Field(
        ..., description='Image source: local path, @/ (project-relative), or URL'
    )
    x: Coordinate
    y: Coordinate
    width: Optional[confloat(ge=0.0)] = Field(
        None, description='Image width (priority 1)'
    )
    height: Optional[confloat(ge=0.0)] = Field(
        None, description='Image height (priority 1)'
    )
    scale: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Image scale factor (priority 2, ignored if width/height specified)',
    )
    fit: Optional[Fit] = Field(
        None,
        description='Image fit mode (priority 3, ignored if width/height or scale specified)',
    )


class PresetNode(BaseNode):
    type: Literal['preset'] = 'preset'
    preset: str = Field(..., description='Preset name (from presets/ directory)')
    params: Optional[Dict[str, Any]] = Field(
        None, description='Preset-specific parameters'
    )


class GradientNode(BaseNode):
    type: Literal['gradient'] = 'gradient'
    steps: conint(ge=2) = Field(..., description='Number of gradient steps')
    direction: Direction = Field(..., description='Gradient direction')
    startColor: constr(pattern=r'^#[0-9A-Fa-f]{6}$') = Field(
        ..., description='Start color (hex format)'
    )
    endColor: constr(pattern=r'^#[0-9A-Fa-f]{6}$') = Field(
        ..., description='End color (hex format)'
    )


class ParamType(Enum):
    number = 'number'
    string = 'string'
    color = 'color'
    boolean = 'boolean'


class ParamDef(BaseModel):
    """Parameter definition for pattern templates"""
    type: ParamType = Field(..., description='Parameter type')
    default: Optional[Any] = Field(None, description='Default value')
    min: Optional[float] = Field(None, description='Minimum value (for numbers)')
    max: Optional[float] = Field(None, description='Maximum value (for numbers)')
    description: Optional[str] = Field(None, description='Description')


class XSGPattern(BaseModel):
    """XSG Pattern definition"""
    name: Optional[str] = Field(None, description='Pattern display name')
    category: Optional[str] = Field(None, description='Pattern category for menu grouping')
    extends: Optional[str] = Field(
        None, description='Extends another pattern (template inheritance)'
    )
    canvas: Optional[Canvas] = Field(None, description='Canvas dimensions')
    params: Optional[Dict[str, ParamDef]] = Field(
        None, description='Parameter definitions (optional, for template patterns)'
    )
    nodes: Optional[
        List[
            Annotated[
                Union[
                    BackgroundNode,
                    RectNode,
                    CircleNode,
                    EllipseNode,
                    LineNode,
                    DirectedLineNode,
                    ImageNode,
                    PresetNode,
                    GradientNode,
                ],
                Field(discriminator='type'),
            ]
        ]
    ] = Field(
        None,
        description='Array of nodes (layers), rendered in order (first = back, last = front)',
    )


# Type aliases for convenience
PatternNode = Union[
    BackgroundNode,
    RectNode,
    CircleNode,
    EllipseNode,
    LineNode,
    DirectedLineNode,
    ImageNode,
    PresetNode,
    GradientNode,
]
