# generated by datamodel-codegen:
#   filename:  playlist.schema.json
#   timestamp: 2025-11-11T06:28:46+00:00
#
# XSG Playlist Format - Pydantic Models
# Manual adjustments:
#   - Renamed Sources1/2/3 → UrlSource, ImageSource, InlineSource
#   - Renamed XsgPlaylistFormat → Playlist

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, confloat, constr


class Order(Enum):
    sequence = 'sequence'
    random = 'random'
    shuffle = 'shuffle'


class Playback(BaseModel):
    order: Order = Field(
        ...,
        description='Playback order: sequence (in order), random (random each time), shuffle (shuffled once)',
    )
    loop: Optional[bool] = Field(True, description='Loop playback')
    defaultDuration: Optional[confloat(ge=0.0)] = Field(
        5000, description='Default duration per item (ms)'
    )


class PatternSource(BaseModel):
    type: Literal['pattern']
    path: str = Field(
        ..., description='Path to pattern file (supports @/, relative, absolute, URL)'
    )
    duration: Optional[confloat(ge=0.0)] = Field(
        None, description='Display duration (ms)'
    )


class UrlSource(BaseModel):
    type: Literal['url']
    url: str = Field(..., description='URL to display (web page)')
    readonly: Optional[bool] = Field(True, description='Disable user interaction')
    duration: Optional[confloat(ge=0.0)] = Field(
        None, description='Display duration (ms)'
    )


class Fit(Enum):
    contain = 'contain'
    cover = 'cover'
    fill = 'fill'


class ImageSource(BaseModel):
    type: Literal['image']
    src: str = Field(
        ..., description='Image source (supports @/, relative, absolute, URL)'
    )
    fit: Optional[Fit] = Field('cover', description='Image fit mode')
    tile: Optional[bool] = Field(
        False, description='Tile image (for character display)'
    )
    tileSize: Optional[confloat(ge=1.0)] = Field(
        None, description='Tile size in pixels (if tile is true)'
    )
    duration: Optional[confloat(ge=0.0)] = Field(
        None, description='Display duration (ms)'
    )


class InlineSource(BaseModel):
    type: Literal['inline']
    pattern: Dict[str, Any] = Field(
        ..., description='Inline pattern definition (XSG pattern format)'
    )
    duration: Optional[confloat(ge=0.0)] = Field(
        None, description='Display duration (ms)'
    )


class Layers(BaseModel):
    min: Optional[confloat(ge=0.0)] = None
    max: Optional[confloat(ge=0.0)] = None


class Constraints(BaseModel):
    presets: Optional[List[str]] = Field(None, description='Allowed presets')
    layers: Optional[Layers] = Field(None, description='Layer count range')
    colors: Optional[List[constr(pattern=r'^#[0-9A-Fa-f]{6}$')]] = Field(
        None, description='Color palette'
    )


class Generator(BaseModel):
    enabled: Optional[bool] = Field(
        False, description='Enable random pattern generation'
    )
    count: Optional[confloat(ge=1.0)] = Field(
        10, description='Number of patterns to generate'
    )
    duration: Optional[confloat(ge=0.0)] = Field(
        3000, description='Default duration per generated pattern (ms)'
    )
    constraints: Optional[Constraints] = Field(
        None, description='Generation constraints'
    )


class Playlist(BaseModel):
    """XSG Playlist definition"""
    playback: Playback
    sources: Optional[List[Union[PatternSource, UrlSource, ImageSource, InlineSource]]] = Field(
        None, description='Explicit sources (patterns, URLs, images)'
    )
    generator: Optional[Generator] = Field(None, description='Random pattern generator')


# Type aliases for convenience
PlaylistSource = Union[PatternSource, UrlSource, ImageSource, InlineSource]
